name: vibe_checker
description: "Vibe Receipt - 공간 무드 영수증"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 상태관리
  flutter_riverpod: ^2.5.1

  # 센서 / 권한
  light_sensor: ^3.0.1
  noise_meter: ^5.0.2
  permission_handler: ^11.3.1

  # 사진 / 파일
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  path: ^1.9.0

  # UI / 폰트 / 애니메이션
  google_fonts: ^6.2.1

  # 캡처 / 저장 / 공유
  screenshot: ^3.0.0
  gal: ^2.3.0
  share_plus: ^10.0.2

  # 유틸
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#F7F5F0"
  color_dark: "#F7F5F0"
  image: assets/images/ic_splah.png
  image_dark: assets/images/ic_splah.png
  android: true
  ios: true
  fullscreen: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
